# Use Node.js 18 Alpine as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install --legacy-peer-deps

# Copy the entire project directory into the container
COPY . .


# Expose port 5000 for HTTPS
EXPOSE 5000

# Run the server
CMD ["node", "server.js"]
